import { Category, Priority } from "./interfaces";

export const categories: Category[] = [
    {
        id: 0,
        name: "Comida",
        value: "Comida",
        icon: "restaurant",
        library: "MaterialIcons",
    },
    {
        id: 1,
        name: "Limpeza",
        value: "Limpeza",
        icon: "cleaning-services",
        library: "MaterialIcons",
    },
    {
        id: 2,
        name: "Bebida",
        value: "Bebida",
        icon: "local-drink",
        library: "MaterialIcons",
    },
    {
        id: 3,
        name: "Gelados",
        value: "Gelados",
        icon: "ice-cream",
        library: "MaterialCommunityIcons",
    },
    {
        id: 4,
        name: "Higiene",
        value: "Higiene",
        icon: "clean-hands",
        library: "MaterialIcons",
    },
    {
        id: 5,
        name: "Vestuário",
        value: "Vestuário",
        icon: "hanger",
        library: "MaterialCommunityIcons",
    },
    {
        id: 6,
        name: "Saúde",
        value: "Saúde",
        icon: "medicinebox",
        library: "AntDesign",
    },
    {
        id: 7,
        name: "Música",
        value: "Música",
        icon: "music",
        library: "FontAwesome",
    },
    {
        id: 8,
        name: "Entretenimento",
        value: "Entretenimento",
        icon: "television-guide",
        library: "MaterialCommunityIcons",
    },
    {
        id: 9,
        name: "Tecnologia",
        value: "Tecnologia",
        icon: "computer",
        library: "MaterialIcons",
    },
    {
        id: 10,
        name: "Jogos",
        value: "Jogos",
        icon: "gamepad",
        library: "FontAwesome",
    },
    {
        id: 11,
        name: "Cosméticos",
        value: "Cosméticos",
        icon: "lipstick",
        library: "MaterialCommunityIcons",
    },
    {
        id: 12,
        name: "Festa",
        value: "Festa",
        icon: "party-popper",
        library: "MaterialCommunityIcons",
    },
    {
        id: 13,
        name: "Brinquedo",
        value: "Brinquedo",
        icon: "puzzle-piece",
        library: "FontAwesome",
    },
    {
        id: 14,
        name: "Ferramentas",
        value: "Ferramentas",
        icon: "build",
        library: "MaterialIcons",
    },
    {
        id: 15,
        name: "Construção",
        value: "Construção",
        icon: "dump-truck",
        library: "MaterialCommunityIcons",
    },
    {
        id: 16,
        name: "Plantas",
        value: "Plantas",
        icon: "flower-outline",
        library: "MaterialCommunityIcons",
    },
    {
        id: 17,
        name: "Animais",
        value: "Animais",
        icon: "pets",
        library: "MaterialIcons",
    },
];

export const priorities: Priority[] = [
    {
        id: 0,
        name: 'SIM',
        value: 'SIM',
        icon: 'star',
        library: 'FontAwesome',
    },
    {
        id: 1,
        name: 'NÂO',
        value: 'NÂO',
        icon: 'star-o',
        library: 'FontAwesome',
    },
];